In [1]:
import numpy as np
import sklearn

In [2]:
data = np.array([[1,10,25,33,40],[50,75,68,99,100]])
classes_def = np.array([[0, 0, 0.1],
                    [1, 0.1, 0.2],
                    [2, 0.2, 0.3],
                    [3, 0.3, 0.4],
                    [4, 0.4, 0.5],
                    [5, 0.5, 0.6],
                    [6, 0.6, 0.7],
                    [7, 0.7, 0.8],
                    [8, 0.8, 0.9],
                    [9, 0.9, 1.0]])

In [3]:
data_normal = data/np.amax(data)
print(data_normal)
print(classes_def.shape[0])

[[0.01 0.1  0.25 0.33 0.4 ]
 [0.5  0.75 0.68 0.99 1.  ]]
10


In [4]:
classes = data_normal
classes_shape = classes.shape
classes = classes.reshape([classes.size])
class_pair = classes_def[0]
#print(classes_def[0])
# ind = np.argwhere(np.logical_and(classes > 0, classes < 0.5))
#print(ind)
#print(classes[ind])
#classes(ind) = class_pair[0]

In [5]:
for class_pair in classes_def:
    print(class_pair)
    ind = np.argwhere(np.logical_and(classes > class_pair[1], classes <= class_pair[2]))
    print(ind)
    classes[ind] = class_pair[0]
classes.reshape(classes_shape)

[0.  0.  0.1]
[[0]
 [1]]
[1.  0.1 0.2]
[]
[2.  0.2 0.3]
[[2]]
[3.  0.3 0.4]
[[3]
 [4]]
[4.  0.4 0.5]
[[5]]
[5.  0.5 0.6]
[]
[6.  0.6 0.7]
[[7]]
[7.  0.7 0.8]
[[6]]
[8.  0.8 0.9]
[]
[9.  0.9 1. ]
[[8]
 [9]]


array([[0., 0., 2., 3., 3.],
       [4., 7., 6., 9., 9.]])

In [6]:
a = np.array([1, 2, 3, 9])
print(np.argwhere(np.logical_and(a>1, a<3)))
for clas in classes_def:
    print(clas)

[[1]]
[0.  0.  0.1]
[1.  0.1 0.2]
[2.  0.2 0.3]
[3.  0.3 0.4]
[4.  0.4 0.5]
[5.  0.5 0.6]
[6.  0.6 0.7]
[7.  0.7 0.8]
[8.  0.8 0.9]
[9.  0.9 1. ]


In [6]:
# Generate classes autmatically for given number of classes
class_num = 5
class_spacing = 1 / class_num
ids = np.linspace(0,class_num-1,class_num)
class_start = np.linspace(0, 1-class_spacing, class_num)
class_end = np.linspace(class_spacing, 1, class_num)
classes_def = np.vstack((ids, class_start, class_end))
classes_def = classes_def.T

In [2]:
import sklearn.datasets
X,y = sklearn.datasets.load_boston(return_X_y=True)
X.shape[0] == y.shape[0]

True